# Generated by Django 5.0.1 on 2024-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='user_type',
            field=models.CharField(default='employee', max_length=20),
        ),
    ]
