# Generated by Django 5.0 on 2024-01-05 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_username', models.CharField(max_length=255)),
                ('employee_password', models.CharField(max_length=255)),
                ('employee_mobile', models.CharField(max_length=15)),
                ('employee_manager_id', models.IntegerField()),
                ('employee_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(default='', max_length=255)),
                ('leave_type', models.CharField(max_length=50)),
                ('leave_description', models.TextField()),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('proof_attachment', models.FileField(default='default_proof_attachment.pdf', upload_to='proof_attachments/')),
                ('application_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=255)),
                ('manager_username', models.CharField(max_length=255)),
                ('manager_password', models.CharField(max_length=255)),
                ('manager_mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
